// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public final class CompteOuterClass {
  private CompteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_Compte_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_Compte_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_CompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_CompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_SoldeStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_SoldeStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetAllComptesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetAllComptesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetAllComptesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetAllComptesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetCompteByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetCompteByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetCompteByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetCompteByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetTotalSoldeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetTotalSoldeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetTotalSoldeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetTotalSoldeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_SaveCompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_SaveCompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_SaveCompteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_SaveCompteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetComptesByTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetComptesByTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_GetComptesByTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_GetComptesByTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_DeleteCompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_DeleteCompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ma_projet_grpc_stubs_DeleteCompteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ma_projet_grpc_stubs_DeleteCompteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014compte.proto\022\024ma.projet.grpc.stubs\"i\n\006" +
      "Compte\022\n\n\002id\030\001 \001(\t\022\r\n\005solde\030\002 \001(\002\022\024\n\014dat" +
      "eCreation\030\003 \001(\t\022.\n\004type\030\004 \001(\0162 .ma.proje" +
      "t.grpc.stubs.TypeCompte\"d\n\rCompteRequest" +
      "\022\r\n\005solde\030\001 \001(\002\022\024\n\014dateCreation\030\002 \001(\t\022.\n" +
      "\004type\030\003 \001(\0162 .ma.projet.grpc.stubs.TypeC" +
      "ompte\"9\n\nSoldeStats\022\r\n\005count\030\001 \001(\005\022\013\n\003su" +
      "m\030\002 \001(\002\022\017\n\007average\030\003 \001(\002\"\026\n\024GetAllCompte" +
      "sRequest\"F\n\025GetAllComptesResponse\022-\n\007com" +
      "ptes\030\001 \003(\0132\034.ma.projet.grpc.stubs.Compte" +
      "\"\"\n\024GetCompteByIdRequest\022\n\n\002id\030\001 \001(\t\"E\n\025" +
      "GetCompteByIdResponse\022,\n\006compte\030\001 \001(\0132\034." +
      "ma.projet.grpc.stubs.Compte\"\026\n\024GetTotalS" +
      "oldeRequest\"H\n\025GetTotalSoldeResponse\022/\n\005" +
      "stats\030\001 \001(\0132 .ma.projet.grpc.stubs.Solde" +
      "Stats\"H\n\021SaveCompteRequest\0223\n\006compte\030\001 \001" +
      "(\0132#.ma.projet.grpc.stubs.CompteRequest\"" +
      "B\n\022SaveCompteResponse\022,\n\006compte\030\001 \001(\0132\034." +
      "ma.projet.grpc.stubs.Compte\"I\n\027GetCompte" +
      "sByTypeRequest\022.\n\004type\030\001 \001(\0162 .ma.projet" +
      ".grpc.stubs.TypeCompte\"I\n\030GetComptesByTy" +
      "peResponse\022-\n\007comptes\030\001 \003(\0132\034.ma.projet." +
      "grpc.stubs.Compte\"!\n\023DeleteCompteRequest" +
      "\022\n\n\002id\030\001 \001(\t\"8\n\024DeleteCompteResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t*&\n\nTypeCo" +
      "mpte\022\013\n\007COURANT\020\000\022\013\n\007EPARGNE\020\0012\374\004\n\rCompt" +
      "eService\022e\n\nAllComptes\022*.ma.projet.grpc." +
      "stubs.GetAllComptesRequest\032+.ma.projet.g" +
      "rpc.stubs.GetAllComptesResponse\022e\n\nCompt" +
      "eById\022*.ma.projet.grpc.stubs.GetCompteBy" +
      "IdRequest\032+.ma.projet.grpc.stubs.GetComp" +
      "teByIdResponse\022e\n\nTotalSolde\022*.ma.projet" +
      ".grpc.stubs.GetTotalSoldeRequest\032+.ma.pr" +
      "ojet.grpc.stubs.GetTotalSoldeResponse\022_\n" +
      "\nSaveCompte\022\'.ma.projet.grpc.stubs.SaveC" +
      "ompteRequest\032(.ma.projet.grpc.stubs.Save" +
      "CompteResponse\022n\n\rComptesByType\022-.ma.pro" +
      "jet.grpc.stubs.GetComptesByTypeRequest\032." +
      ".ma.projet.grpc.stubs.GetComptesByTypeRe" +
      "sponse\022e\n\014DeleteCompte\022).ma.projet.grpc." +
      "stubs.DeleteCompteRequest\032*.ma.projet.gr" +
      "pc.stubs.DeleteCompteResponseB\030\n\024ma.proj" +
      "et.grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ma_projet_grpc_stubs_Compte_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ma_projet_grpc_stubs_Compte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_Compte_descriptor,
        new java.lang.String[] { "Id", "Solde", "DateCreation", "Type", });
    internal_static_ma_projet_grpc_stubs_CompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ma_projet_grpc_stubs_CompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_CompteRequest_descriptor,
        new java.lang.String[] { "Solde", "DateCreation", "Type", });
    internal_static_ma_projet_grpc_stubs_SoldeStats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ma_projet_grpc_stubs_SoldeStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_SoldeStats_descriptor,
        new java.lang.String[] { "Count", "Sum", "Average", });
    internal_static_ma_projet_grpc_stubs_GetAllComptesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ma_projet_grpc_stubs_GetAllComptesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetAllComptesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ma_projet_grpc_stubs_GetAllComptesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ma_projet_grpc_stubs_GetAllComptesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetAllComptesResponse_descriptor,
        new java.lang.String[] { "Comptes", });
    internal_static_ma_projet_grpc_stubs_GetCompteByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ma_projet_grpc_stubs_GetCompteByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetCompteByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ma_projet_grpc_stubs_GetCompteByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ma_projet_grpc_stubs_GetCompteByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetCompteByIdResponse_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_ma_projet_grpc_stubs_GetTotalSoldeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ma_projet_grpc_stubs_GetTotalSoldeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetTotalSoldeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ma_projet_grpc_stubs_GetTotalSoldeResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ma_projet_grpc_stubs_GetTotalSoldeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetTotalSoldeResponse_descriptor,
        new java.lang.String[] { "Stats", });
    internal_static_ma_projet_grpc_stubs_SaveCompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ma_projet_grpc_stubs_SaveCompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_SaveCompteRequest_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_ma_projet_grpc_stubs_SaveCompteResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ma_projet_grpc_stubs_SaveCompteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_SaveCompteResponse_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_ma_projet_grpc_stubs_GetComptesByTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ma_projet_grpc_stubs_GetComptesByTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetComptesByTypeRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_ma_projet_grpc_stubs_GetComptesByTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ma_projet_grpc_stubs_GetComptesByTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_GetComptesByTypeResponse_descriptor,
        new java.lang.String[] { "Comptes", });
    internal_static_ma_projet_grpc_stubs_DeleteCompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ma_projet_grpc_stubs_DeleteCompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_DeleteCompteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ma_projet_grpc_stubs_DeleteCompteResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ma_projet_grpc_stubs_DeleteCompteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ma_projet_grpc_stubs_DeleteCompteResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
