// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface GetComptesByTypeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ma.projet.grpc.stubs.GetComptesByTypeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ma.projet.grpc.stubs.Compte comptes = 1;</code>
   */
  java.util.List<ma.projet.grpc.stubs.Compte> 
      getComptesList();
  /**
   * <code>repeated .ma.projet.grpc.stubs.Compte comptes = 1;</code>
   */
  ma.projet.grpc.stubs.Compte getComptes(int index);
  /**
   * <code>repeated .ma.projet.grpc.stubs.Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <code>repeated .ma.projet.grpc.stubs.Compte comptes = 1;</code>
   */
  java.util.List<? extends ma.projet.grpc.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <code>repeated .ma.projet.grpc.stubs.Compte comptes = 1;</code>
   */
  ma.projet.grpc.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
