// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface GetComptesByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ma.projet.grpc.stubs.GetComptesByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ma.projet.grpc.stubs.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ma.projet.grpc.stubs.TypeCompte type = 1;</code>
   * @return The type.
   */
  ma.projet.grpc.stubs.TypeCompte getType();
}
